name: Backend Service Deployment

on:
  push:
    branches:
      - dev
      - qa
      - staging
      - main
  pull_request:
    types: [closed]
    branches:
      - main
      - staging
      - qa
      - dev
      - sandbox
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        type: choice
        options:
          - dev
          - qa
          - staging
          - main
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - qa
          - staging
          - prod
      skip_deploy:
        description: 'Skip deployment (only build and push)'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: finefindslk/base/node-services
  SERVICES_ENV: >-
    ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 
    github.ref == 'refs/heads/main' && 'prod' || 
    github.ref == 'refs/heads/staging' && 'staging' || 
    github.ref == 'refs/heads/qa' && 'qa' || 
    github.ref == 'refs/heads/dev' && 'dev' ||
    'sandbox' }}
  ECR_REPOSITORY_BACKEND: finefinds-services-${{ github.event_name == 'workflow_dispatch' && inputs.environment || github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || github.ref == 'refs/heads/qa' && 'qa' || github.ref == 'refs/heads/dev' && 'dev' || 'sandbox' }}

jobs:
  input_check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check for inputs to validate
        id: input_check
        run: |
          echo "Input Env: ${{inputs.environment }}"
          echo "Env: ${{env.SERVICES_ENV}}"
          echo "Branch: ${{inputs.branch}}"
          echo "Skip Deploy: ${{inputs.skip_deploy}}"
          echo "Role Id: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-test"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Environment: ${{ github.event.repository.name }}"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-test
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          mask-aws-account-id: false

  test:
    needs: input_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build
        run: npm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-test
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Generate version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(date +'%Y%m%d').${{ github.run_number }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDPLATFORM=${{ runner.arch }}
            TARGETPLATFORM=${{ runner.arch }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ steps.version.outputs.version }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Save version for deployment
        run: echo "${{ steps.version.outputs.version }}" > version.txt
        
      - name: Upload version file
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

  deploy-sandbox:
    needs: build-and-push
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') && (github.ref == 'refs/heads/sandbox' || github.event.pull_request.base.ref == 'sandbox' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'sandbox')) }}
    runs-on: ubuntu-latest
    environment: sandbox
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-sandbox
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Deploy to ECS
        run: |
          VERSION=$(cat version.txt)
          aws ecs update-service \
            --cluster finefinds-sandbox \
            --service finefinds-backend \
            --force-new-deployment \
            --task-definition finefinds-backend:$VERSION

  deploy-dev:
    needs: build-and-push
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') && (github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev')) }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-finefinds-services-dev
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Deploy to ECS
        run: |
          VERSION=$(cat version.txt)
          aws ecs update-service \
            --cluster finefinds-dev \
            --service finefinds-backend \
            --force-new-deployment \
            --task-definition finefinds-backend:$VERSION

  deploy-qa:
    needs: build-and-push
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') && (github.ref == 'refs/heads/qa' || github.event.pull_request.base.ref == 'qa' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'qa')) }}
    runs-on: ubuntu-latest
    environment: qa
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-finefinds-services-qa
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Deploy to ECS
        run: |
          VERSION=$(cat version.txt)
          aws ecs update-service \
            --cluster finefinds-qa \
            --service finefinds-backend \
            --force-new-deployment \
            --task-definition finefinds-backend:$VERSION

  deploy-staging:
    needs: build-and-push
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') && (github.ref == 'refs/heads/staging' || github.event.pull_request.base.ref == 'staging' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'staging')) }}
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-finefinds-services-staging
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Deploy to ECS
        run: |
          VERSION=$(cat version.txt)
          aws ecs update-service \
            --cluster finefinds-staging \
            --service finefinds-backend \
            --force-new-deployment \
            --task-definition finefinds-backend:$VERSION

  deploy-prod:
    needs: build-and-push
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') && (github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')) }}
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-finefinds-services-prod
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          
      - name: Deploy to ECS
        run: |
          VERSION=$(cat version.txt)
          aws ecs update-service \
            --cluster finefinds-prod \
            --service finefinds-backend \
            --force-new-deployment \
            --task-definition finefinds-backend:$VERSION

  notify:
    needs: [deploy-sandbox, deploy-dev, deploy-qa, deploy-staging, deploy-prod]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification (Success)
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL }}",
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": ":white_check_mark: *Backend Services Deployment Succeeded*",
                  "fields": [
                    { "title": "Environment", "value": "${{ env.SERVICES_ENV }}", "short": true },
                    { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                    { "title": "Actor", "value": "${{ github.actor }}", "short": true },
                    { "title": "Commit", "value": "${{ github.sha }}", "short": false }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Workflow",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }

      - name: Slack Notification (Failure)
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL }}",
              "attachments": [
                {
                  "color": "#ff0000",
                  "pretext": ":x: *Backend Services Deployment Failed*",
                  "fields": [
                    { "title": "Environment", "value": "${{ env.SERVICES_ENV }}", "short": true },
                    { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                    { "title": "Actor", "value": "${{ github.actor }}", "short": true },
                    { "title": "Commit", "value": "${{ github.sha }}", "short": false }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Workflow",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }